import { NativeModules } from 'react-native';

const { EscPosPrinter } = NativeModules;

const EscPosPrinterConstants: Record<string, number> =
  EscPosPrinter.getConstants();

export enum PrinterGetSettingsType {
  PRINTER_SETTING_PAPERWIDTH = EscPosPrinterConstants.PRINTER_SETTING_PAPERWIDTH,
  PRINTER_SETTING_PRINTDENSITY = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY,
  PRINTER_SETTING_PRINTSPEED = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED,
}

export enum GetPrinterSettingsPaperWidthValues {
  PRINTER_SETTING_PAPERWIDTH58_0 = EscPosPrinterConstants.PRINTER_SETTING_PAPERWIDTH58_0,
  PRINTER_SETTING_PAPERWIDTH60_0 = EscPosPrinterConstants.PRINTER_SETTING_PAPERWIDTH60_0,
  PRINTER_SETTING_PAPERWIDTH70_0 = EscPosPrinterConstants.PRINTER_SETTING_PAPERWIDTH70_0,
  PRINTER_SETTING_PAPERWIDTH76_0 = EscPosPrinterConstants.PRINTER_SETTING_PAPERWIDTH76_0,
  PRINTER_SETTING_PAPERWIDTH80_0 = EscPosPrinterConstants.PRINTER_SETTING_PAPERWIDTH80_0,
}

export enum GetPrinterSettingsDensityValues {
  PRINTER_SETTING_PRINTDENSITYDIP = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITYDIP,
  PRINTER_SETTING_PRINTDENSITY70 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY70,
  PRINTER_SETTING_PRINTDENSITY75 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY75,
  PRINTER_SETTING_PRINTDENSITY80 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY80,
  PRINTER_SETTING_PRINTDENSITY85 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY85,
  PRINTER_SETTING_PRINTDENSITY90 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY90,
  PRINTER_SETTING_PRINTDENSITY95 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY95,
  PRINTER_SETTING_PRINTDENSITY100 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY100,
  PRINTER_SETTING_PRINTDENSITY105 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY105,
  PRINTER_SETTING_PRINTDENSITY110 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY110,
  PRINTER_SETTING_PRINTDENSITY115 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY115,
  PRINTER_SETTING_PRINTDENSITY120 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY120,
  PRINTER_SETTING_PRINTDENSITY125 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY125,
  PRINTER_SETTING_PRINTDENSITY130 = EscPosPrinterConstants.PRINTER_SETTING_PRINTDENSITY130,
}

export enum GetPrinterSettingsPrintSpeedValues {
  PRINTER_SETTING_PRINTSPEED1 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED1,
  PRINTER_SETTING_PRINTSPEED2 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED2,
  PRINTER_SETTING_PRINTSPEED3 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED3,
  PRINTER_SETTING_PRINTSPEED4 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED4,
  PRINTER_SETTING_PRINTSPEED5 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED5,
  PRINTER_SETTING_PRINTSPEED6 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED6,
  PRINTER_SETTING_PRINTSPEED7 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED7,
  PRINTER_SETTING_PRINTSPEED8 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED8,
  PRINTER_SETTING_PRINTSPEED9 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED9,
  PRINTER_SETTING_PRINTSPEED10 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED10,
  PRINTER_SETTING_PRINTSPEED11 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED11,
  PRINTER_SETTING_PRINTSPEED12 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED12,
  PRINTER_SETTING_PRINTSPEED13 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED13,
  PRINTER_SETTING_PRINTSPEED14 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED14,
  PRINTER_SETTING_PRINTSPEED15 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED15,
  PRINTER_SETTING_PRINTSPEED16 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED16,
  PRINTER_SETTING_PRINTSPEED17 = EscPosPrinterConstants.PRINTER_SETTING_PRINTSPEED17,
}
