name: Bug report
description: Report an issue related to react-native-esc-pos-printer here.
body:
  - type: markdown
    attributes:
      value: |
        Before you start:
        - Make sure to check whether there are similar issues in the repository
  - type: markdown
    attributes:
      value: |
        ## Required information
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear, concise, and descriptive explanation of the bug. Include screenshots or a video if needed. Tell us what were you expecting to happen instead of what is happening now.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: lib-version
    attributes:
      label: react-native-esc-pos-printer version
      description: What version of react-native-esc-pos-printer are you using?
      placeholder: 4.0.1
    validations:
      required: true

  - type: input
    id: react-native-version
    attributes:
      label: React Native version
      description: What version of react-native are you using?
      placeholder: 0.73.1
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: On what platform is your application running?
      multiple: true
      options:
        - Android
        - iOS
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Additional information

        Providing as much information as possible greatly helps us with reproducing the issues.

  - type: dropdown
    id: workflow
    attributes:
      label: Workflow
      description: How is your application managed?
      options:
        - React Native
        - Expo Go
        - Expo Dev Client

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: What React Native architecture your application is running on? Currently, the default architecture on React Native is Paper so if you haven't changed it in your application select this option.
      options:
        - Paper (Old Architecture)
        - Fabric (New Architecture)

  - type: dropdown
    id: build-type
    attributes:
      label: Build type
      description: What is the build configuration/variant of your native app and JavaScript bundle mode?
      options:
        - Debug app & dev bundle
        - Release app & production bundle
        - Debug app & production bundle
        - Release app & dev bundle
        - Other (please specify)

  - type: dropdown
    id: emulator
    attributes:
      label: Device
      description: How are you running your application?
      options:
        - iOS simulator
        - Android emulator
        - Real device

  - type: input
    id: device-model
    attributes:
      label: Device model
      description: What device you are experiencing this problem on? Specify full device name along with the version of the operating system it's running.
      placeholder: ex. Samsung Galaxy A22 (Android 12)

  - type: dropdown
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: I searched for similar issues in the repository.
      options:
        - 'Yes'
    validations:
      required: true
